# Generated by Django 3.2.9 on 2021-12-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightApp', '0002_alter_reservation_flight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='middlename',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
