# Generated by Django 3.2.9 on 2021-12-27 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Eemployee',
            new_name='Employee',
        ),
    ]
